version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh:ro  # For GitHub access
    ports:
      - "8888:8888"  # Jupyter
      - "8000:8000"  # FastAPI
    environment:
      - PYTHONPATH=/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    
  # Optional: Add a service for model serving
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload