[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlproject"
version = "0.1.0"
description = "ML Development Environment"
readme = "README.md"
requires-python = ">=3.9"



